### PR TITLE
[WIP]: new deployment config

### PR DESCRIPTION
**Pull request by Xylakant**
add app servers, workers are still commented out. 

This deployment config properly attempts to deploy to app0/app1. It currently fails due to a missing database config.

It requires the following ssh config:

    Host wheelmap-jmp
      SendEnv GIT_*
      ForwardAgent yes
      Hostname 185.56.129.83
    
    Host *.node.production
      ForwardAgent yes
      ProxyCommand ssh wheelmap-jmp -W %h:%p

Name resolution for app0.node.consul will happen on the jumphost and since the jumphost is part of the consul cluster it will succeed.

### CODE REVIEW

**Comment by Hoverbear** [comment]
Remaining:

* [ ] Compile assets only on asset server.
* [ ] Unicorn commands on app server
* [ ] Worker should do delayed job task.

**Comment by Hoverbear** [comment]
Fixed the worker in 55369032ed13671e746bdb5821316904c92f333d (which I accidentally pushed to the main branch without a PR, sorry)

**Comment by Hoverbear** [comment]
Sudoers config, as we discussed, should be fine. I think this was related to a stale branch or a non-updated chef run.

**Comment by Xylakant** [comment]
rebased against feature/infra-rebuild, can be merged.

**Comment by Hoverbear** [comment]
LGTM. Merging.

**Pull request merged**
