### PR TITLE
Fix styling errors in the toolbar in Firefox (#36)

### PR DESCRIPTION
**Pull request by yeralin**
Hope, it is fine now :)

### CODE REVIEW

**Comment by lennerd** [comment]
Okay, sorry for the confusion. But you need to pull the newest changes to your master first and than rebase your UI branch so this PR only will contain your own commit defff32.

**Comment by lennerd** [comment]
And you don't need to delete this PR. It will be updated as soon as you update your branches histories.

**Comment by yeralin** [comment]
Lol. Ok thanks :) I'll do it in a sec

**Comment by yeralin** [comment]
Seems like I have everything up to date.

No new changes :(

image

**Comment by lennerd** [comment]
Did you try to merge the current `master` into your `UI` branch?

Git can be confusing. :expressionless:

**Comment by yeralin** [comment]
image

No progress. Keep saying that everything is fine

**Comment by lennerd** [comment]
Okay, please try the following:

```
git checkout master
git reset --hard eff4044769b50c39a1d55439558ff66c15ae3222
git pull
git checkout UI
git reset --hard eff4044769b50c39a1d55439558ff66c15ae3222
git cherry-pick defff3221dd993b500786aca5943c9577b0a6509
git rebase master
git push -f
```

Be carefull with this. We will reset your local UI branch to cherry pick your single commit from the remote UI branch. It's easy something get lost in this process.

**Comment by lennerd** [comment]
Ah now I see the problem. The master is not updated, because your fork is not up to date with our main repository.

You first need update your upstream: https://help.github.com/articles/syncing-a-fork/

**Comment by yeralin** [comment]
ok, check out now. Everything is gotta be fine.

**Comment by lennerd** [comment]
I'm sorry, but this PR still contains multiple commits from an old master branch.

screenshot 2015-10-06 16 13 19

Did you saw my comment on your changes?

**Comment by yeralin** [comment]
image

**Comment by lennerd** [comment]
You need to fetch the current master from upstream before you make changes in your own tree. Did you try to work with tools like [Sourcetree](https://www.sourcetreeapp.com/)? It's also available for Windows and maybe helps to understand the state of your history.

**Comment by yeralin** [comment]
What if I remove my fork, fork you project again, and add my changes? Would it be somehow easier?

**Comment by lennerd** [comment]
Maybe yes. But should not forget to create checkout out a branch for this bugfix before you commit your changes, so you can use this branch to make a pull request from.

Thank you for your work and sorry for the confusion.

**Comment by lennerd** [comment]
I post my comment to your changes here to don't lose it when you delete your fork.

I was able to fix it by making some changes in the carret class. I removed it floating property 
(https://github.com/sozialhelden/wheelmap/blob/e6ee8ecb01d4d6e1ed24116225095f9b2a36ef75/app/assets/stylesheets/relaunch/_bootstrap-select.css.scss#L5) which fixed the wrong position in all bootstrap dropdowns.

The only thing left now is the wrong spacing inside the toilet filter, which is maybe a padding problem, and the wrong position of the carret in the category filter, which we can handle by some extra css for this specific dropdown. Does this work for you too?

**Comment by yeralin** [comment]
I see what you are saying. I just tried to do that. It still breaks WC dropdown button, and it needs more work

**Comment by lennerd** [comment]
I will fork your repository and make a PR for this on your fork. Let's see, if we can make this work. :wink:

**Pull request closed without merging**
