### PR TITLE
Add compass based icon sprite and CSS class generation.

### PR DESCRIPTION
**Pull request by lennerd**
This PR refactors the generation of the icon sprite file to simplify the process when new node types and therefore new icons were added.

Compass has a built in feature to generate sprite files and to provide the corresponding CSS values (`background-image`, `background-position`, icon file name list) to be used in the icon CSS classes. No more extra task and copy and paste hell when we add new node type.

- [x] Remove old icon sprite task
- [x] Update wiki

### CODE REVIEW

**Comment by lennerd** [comment]
Depends on #208, which needs to be merged first

**Comment by 1000miles** [comment]
@lennerd Great idea to replace the script with compass. \o/ Can you please remove the second task (update wiki) from this PR or set this PR to WIP? Otherwise it might be lost after merge. :)

**Comment by lennerd** [comment]
The wiki is updated. I also added a part about creating the corresponding zip file for the mobile apps.

**Comment by 1000miles** [comment]
We have tested your branch on the staging server and saw that the icons are not displayed while locally they are displayed correctly. Can you please test your latest changes again?

**Comment by lennerd** [comment]
Sounds like Cloudflaire is interferring when providing the stylesheet where the sprite url is provided. I will take a look onto the server and talk to Timo to see how we can improve this.

**Comment by lennerd** [comment]
Thanks @1000miles for testing and sorry for the delayed response. I spoke to @thermann78 and also tested the responsive for the stylesheet. It's not cached by Cloudflare, so the Problem must be somewhere else.

I have the feeling, that our asset precompiling is not working correctly with sprites coming from Compass. I had made the same experience with some bad combinations of the old Asset Pipeline of Rails 3 and the browserify gem. Here we needed to clear the shared asset folder in order to have new assets.

I'm not sure if Rails can be configured to check also for new image sprites? Or we need to wait for Rails 3 in order to update? I'm a bit 404 about this one.

**Comment by lennerd** [comment]
@1000miles @schultyy I just checked the stylesheet and realized that it does not contain the newest changes in https://github.com/sozialhelden/wheelmap/blob/enhancement/icons-sprite/app/assets/stylesheets/relaunch/_icons.css.scss#L46-L47 which moved the `width` and `height` properties to the `.leaflet-marker-icon` class to not repeat it for every marker. So this leads me to the conclusion that the whole stylesheet was not rebuilt on deployment.

**Comment by lennerd** [comment]
Just deployed this again on staging. Everything is working fine now.

**Comment by schultyy** [comment]
@lennerd I changed the output directory of the `zip` command. It now places `icons.zip` and `markers.zip` in `public/` directly.

**Comment by schultyy** [comment]
Can be merged.

**Comment by lennerd** [comment]
Nice, thank you! 👍

**Pull request merged**
