### PR TITLE
Fix the language picker by using a dedicated javascript

### PR DESCRIPTION
**Pull request by Hoverbear**
Resolves the issues in https://github.com/sozialhelden/wheelmap/pull/544

### CODE REVIEW

**Comment by schultyy** [comment]
I deployed this on Staging but it seems like the problem still exists. I checked the network tab: 
screen shot 2017-02-28 at 15 06 00

@Hoverbear can you have a look at this?

**Comment by Hoverbear** [comment]
This must be to do with the asset pipeline?

screen shot 2017-02-28 at 16 17 21

**Comment by Hoverbear** [comment]
danger

**Comment by schultyy** [comment]
🐻

**Comment by schultyy** [comment]
Deployed on [production](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170301134404)

**Pull request merged**
