### PR TITLE
Fix image upload message delay and max filesize.

### PR DESCRIPTION
**Pull request by lennerd**

### CODE REVIEW

**Comment by lennerd** [comment]
This PR does not contain translations coming from Transifex. Either we create a seperate PR for this or we add them directly.

@holgerd Do we need translated error messages? At the moment we have the default messages from Dropzone.js library.

**Comment by 1000miles** [comment]
@lennerd I would suggest to finish all validation options first and then focus on translations to keep it clean for debugging.

**Comment by lennerd** [comment]
Okay, then this PR can be merged or maybe simply extended with your changes.

**Comment by 1000miles** [comment]
@lennerd Can you please deploy your last commit 33f4ea0 on staging (if you haven't done it yet), so we can final test it before we merge?

**Comment by lennerd** [comment]
screenshot 2016-07-07 10 00 13

I deployed quite actively. 😆  So yes, the last commit is already on staging. 😉

**Comment by lennerd** [comment]
screenshot 2016-07-06 13 33 43

**Comment by schultyy** [comment]
lgtm

**Pull request merged**
