### PR TITLE
Tx/fetch translations 20170131

### PR DESCRIPTION
**Pull request by 1000miles**
This PR adds the latest translations from transifex. 

It seems the `image upload alert text` has yet not been translated to the other languages, e.g. AR, BG, CA, etc.

Please don't merge. We will wait a few more days until more translations are ready to be fetched.

### CODE REVIEW

**Comment by Hoverbear** [comment]
Looks like "node_photos alert" text still is missing some translations.

**Comment by 1000miles** [comment]
Yeah, we are waiting for @Svenyo to give us some feedback, if we can merge and deploy the current translation batch.

**Comment by Svenyo** [comment]
@1000miles @Hoverbear Yes, go ahead. There should be around 1,500 new strings translated by now.

**Comment by 1000miles** [comment]
Thanks, @Svenyo . Fetched the latest translations today again. Can you please click on `approve` here, so we can merge this PR?

Here is a link how to do this: https://help.github.com/articles/approving-a-pull-request-with-required-reviews/

**Comment by 1000miles** [comment]
Deployed to live server with [production-20170330110932](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170330110932) today.

**Pull request merged**
