### PR TITLE
Ensure accessibility.cloud CSS goes through asset pipeline

### PR DESCRIPTION
**Pull request by opyh**
This is hopefully the last necessary fix for getting https://github.com/sozialhelden/wheelmap/pull/620 through the door.

For testing locally, use:
- http://192.168.33.10:3000/nodes/429735547 (5 PoIs nearby)
- http://192.168.33.10:3000/nodes/86001833 (3 PoIs nearby)

### CODE REVIEW

**Comment by 1000miles** [comment]
@opyh Thanks for the PR. I checked into your branch and precompiled the assets in development. It seems your current PR produces a source map (`accessibility.cloud-3.2.1-2350f78a.css.map`) that can not be found. 



1. Question: Does this really need to be a source map or is there an alternative you could check in?
2. I learned that we might need to:
 - add the accessibility.cloud file to the Rails assets pipeline precompiling process at `config/initializers/assets.rb` 
 - use a subdirectory for source map to exclude it from the precompiling process

Please find more infos here: https://stackoverflow.com/questions/24902034/asset-pipeline-ignore-ceratin-file-types

3. Did you see the overlapping bbox coordinates when using the search (please see screen above)?
4. Is there an example node which I can test the widget rendering in development mode with less pois?

**Comment by opyh** [comment]
1. I just removed the source map reference, I think that's the fastest solution.
2. We should not include the CSS globally, or should we? This way it would be included in every subpage, even the ones that do not include the widget.
3. Fixed!
4.
  - https://staging.wheelmap.org/nodes/304897065 (no PoIs nearby)
  - https://staging.wheelmap.org/nodes/354217518 (3 PoIs nearby)

**Comment by 1000miles** [comment]
@opyh 

1. Sounds good, thank you.
2. Right, makes sense if globally is not required.
3. Merci for fixing.
4. Thanks for the staging example. However, here is a local example that we all should have in common (initial data set): http://localhost:3000/nodes/429735547

**Comment by 1000miles** [comment]
@opyh cc @holgerd 

FYI, this PR is deployed to staging with release [20170612134158](https://github.com/sozialhelden/wheelmap/releases/tag/staging-20170612134158). What's the next step here? You need to switch on the widget for @holgerd to do the final review?

**Comment by opyh** [comment]
@holgerd @Svenyo You can one of you check the feature on https://staging.wheelmap.org/nodes/2708872307 and us give your go for production?

If you want to see how Jaccede's data looks with the new widget, you can switch the Jaccede source on and off using the 'Only a draft' checkbox on this page: https://www.accessibility.cloud/sources/JiTwDMcX5c8erJx95/settings

@Svenyo, if you do this: To get access to accessibilty.cloud, you must
- register on https://www.accessibility.cloud/join using your @sozialhelden.de email address
- be approved by me or another admin.

**Comment by Svenyo** [comment]
Dear @opyh, when I click on the link I see only AXS-Maps data. Is that correct? 

I registered an account on accessibility cloud as recommended. Waiting for approval in order to check the switch on and off function.

**Comment by opyh** [comment]
Hey @Svenyo, yep, that's correct. I approved your account so you have access to the data source settings. Hope everything works :)

**Comment by 1000miles** [comment]
Deployed to production today with release [20170626103531](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170626103531).

Screenshot result:
jaccede_20170626

**Comment by 1000miles** [comment]
Example link to look up: https://wheelmap.org/nodes/2708872307

**Pull request merged**
