### PR TITLE
Adding links about GDPR compliance to the footer

### PR DESCRIPTION
**Pull request by spacekookie**
This is addressing issue #679 but not done yet. We need to figure out how to handle the translations for the newly added link. Right now no text is present (not even German/ English)

**Note** This PR also adds translations for #669

### CODE REVIEW

**Comment by holgerd** [comment]
@spacekookie Thanks for this. I do not understand: Do you need text from us? cc @Svenyo

**Comment by spacekookie** [comment]
Your original issue said to discuss translations with you. We can of course only add the German and English values ourselves, but then I'm not sure what users visiting for another language would encounter.

**Comment by Svenyo** [comment]
Hi @spacekookie, please find the general workflow for translations here: https://github.com/sozialhelden/wheelmap/wiki/Add-new-translations 
What's most important is that...

1. new text strings need to be integrated in the source language (English) of the corresponding .yml file and 
2. uploaded again in Transifex. 
3. When this is done, please send me a short message, 
4. then I can start the procedure for getting the translations done with Transifex. 
5. I'll send you a message, when translations are completed and the .yml files are ready for use.

**Comment by spacekookie** [comment]
Ping @Svenyo, you can start the translation process now

**Comment by Svenyo** [comment]
Hi @spacekookie, I can't find the string in Transifex. Is the updated source language (English) already uploaded?

**Comment by spacekookie** [comment]
Hey @Svenyo, I added the modified `.yml` files for transifex in this pull request:

 - German: https://github.com/spacekookie/wheelmap/blob/5081f719270e239430afc0a0b4bdd8d644115e36/config/locales/de/relaunch.yml
 - English: https://github.com/spacekookie/wheelmap/blob/5081f719270e239430afc0a0b4bdd8d644115e36/config/locales/en/relaunch.yml

From what I understand these need to be provided to transifex so we can download the translated files for wheelmap.

**Comment by spacekookie** [comment]
According to [this wiki article](https://github.com/sozialhelden/wheelmap/wiki/Translation-Guide) I should just upload the `.yml` files with the new keys. Then:

> 2. The updated resource files are to be uploaded to Transifex by the product manager

So I was under the assumption that you had to do that.

**Comment by Svenyo** [comment]
Okay, good!

**Comment by Svenyo** [comment]
Yes, good idea. Is it possible to deploy it to staging first for the review before it goes to production?

**Comment by spacekookie** [comment]
@Svenyo Alright, we're merging this PR now then and deploying to staging

**Comment by Svenyo** [comment]
Dear @spacekookie, just checked on staging: For the German version everything looks fine on staging, for the English version as well. When choosing all other languages, the English wording and privacy policy content should appear, though. Please adjust!

**Comment by 1000miles** [comment]
@Svenyo cc @spacekookie 

What you currently see on staging in the footer at the moment ("Datenbestimmungen" on all pages except for English locale) is expected behavior. :) `:de` is the default locale in the wheelmap project while `:en` is the default locale for translations which explains why the **"Datenschutzbestimmungen"** appears on all other locale pages that don't have the translations yet.

**Pull request merged**
