### PR TITLE
Update to devise 3

### PR DESCRIPTION
**Pull request by schultyy**
This PR updates Devise to version 3.1. This introduces the following changes:

- A secret key is needed. In development this is loaded from a `.env` file, in production the `DEVISE_SECRET_KEY` environment variable must be available
- The mailer for confirmation mails is slightly adapted to reflect the changes made in Devise 3

/cc @Xylakant @thermann78 

*UPDATE*:
To have the `DEVISE_SECRET_KEY` available on staging and production we use dotenv for now there as well. Before we used it only in development and test.

### CODE REVIEW

**Comment by skade** [comment]
As discussed: :+1:

**Comment by justahero** [comment]
A few small things to note:

* in Devise 3.1 the module `Devise::Models::TokenAuthenticatable` is deprecated and removed from Devise 3.2, the User class still includes it
* all view mailers need to use the `@token` attribute

**Comment by schultyy** [comment]
Added @justahero's custom `TokenAuthenticable` strategy and adapted all mailer views to use the `@token` attribute.

**Comment by schultyy** [comment]
We still need to figure out when to merge and deploy this because it requires some changes to the server setup.

**Comment by justahero** [comment]
Most of the information is taken from the [Devise 3.1 upgrade guide](http://blog.plataformatec.com.br/2013/08/devise-3-1-now-with-more-secure-defaults/). The guide also contains a [link](https://gist.github.com/josevalim/fb706b1e933ef01e4fb6) to a few implementations of the `TokenAuthenticable` authentication mechanism.

**Comment by justahero** [comment]
Looks good to me so far.

**Pull request merged**
