### PR TITLE
Multipolygon -> Geometry for MySQL 5.7

### LINKED ISSUE #355: MySQL 5.7: Failing tests with Cannot get geometry object from data you send to the GEOMETRY field
When running the tests with MySQL 5.7, we encounter the following error:

```
Mysql2::Error: Cannot get geometry object from data you send to the GEOMETRY field: INSERT INTO `regions` (`created_at`, `grenze`, `lft`, `name`, `rgt`, `slug`, `updated_at`) VALUES ('2016-08-08 14:04:51', GeomFromWKB(0x00000000030000000100000005402a2d36f7e3d1cc404a2b463497b741402b8595feda6613404a2b463497b741402b8595feda6613404a567620ee8d11402a2d36f7e3d1cc404a567620ee8d11402a2d36f7e3d1cc404a2b463497b741,0), 1, 'Berlin', 2, 'berlin', '2016-08-08 14:04:51')
```

### PR DESCRIPTION
**Pull request by Hoverbear**
Might fix #355 #354 .

Please review and test. I tested in an Ubuntu docker container and encountered no issues, but I'm also not entirely sure what might be affected by this change.

### CODE REVIEW

**Comment by Xylakant** [comment]
hmm. this is problematic. We'd need a migration to change the existing database and a migration path for the existing data. What's the difference between Multipolygon and Geometry?

**Comment by Xylakant** [comment]
the mysqlspatial adapter doesn't seem to support multipolygon.

**Comment by Xylakant** [comment]
it looks like the the https://github.com/rgeo/activerecord-mysql2spatial-adapter is not well supported since at least a year.

**Comment by Hoverbear** [comment]
I kind of just "discovered" this while looking around. This is definitely not a complete pull request if we choose to go this route. :)

**Comment by Hoverbear** [comment]
Hmm... Is there a better alternative?

**Comment by Hoverbear** [comment]
Closing due to staleness.

**Pull request closed without merging**
