### PR TITLE
Fix invalid locale error

### PR DESCRIPTION
**Pull request by schultyy**
PR for #242 

We queue this initializer after every other initializer + Rails because Rails itself sets `I18n.enforce_available_locales` to true where we require it be `false`.
The code in `lib/rack_i18n_locale_switcher.rb` depends on `I18n.enforce_available_locales` to be `false`.

This fixes the problem for now but is not optimal yet. We need to figure out if we actually need the `rack_i18n_locale_switcher.rb` generally.

### CODE REVIEW

**Comment by justahero** [comment]
You could check if setting the option `I18n.enforce_available_locales ` in the file `config/application.rb` avoids the logic with the after hook.

**Comment by schultyy** [comment]
@justahero tried it but doesn't work.

**Comment by schultyy** [comment]
Deployed it on staging and tested it. Language switching works so far.

**Comment by 1000miles** [comment]
Works on my machine too and looks good to me. 
Thank you! 🍔

**Pull request merged**
