### PR TITLE
Fixed Ticket #36

### PR DESCRIPTION
**Pull request by yeralin**
Fixed. Implemented using Flexboxes. Flexbox doesn't work with buttons in Firefox, so I had to use additional div inside class="corrector".

### CODE REVIEW

**Comment by yeralin** [comment]
Check it out now. It all should be up to date

**Comment by lennerd** [comment]
Did you see my comment in your last PR?

**Comment by lennerd** [comment]
Anyway, PR looks good! :+1:

**Comment by lennerd** [comment]
@yeralin Did you have time to check my changes?

**Pull request merged**
