### PR TITLE
WIP: Add new node types

### PR DESCRIPTION
**Pull request by lennerd**

### CODE REVIEW

**Comment by lennerd** [comment]
@1000miles I startet to dig out my stuff for creating the new node types. Unfortunately I lost some of my seeds while creating a new branch for this.

I'm not quite sure, how seeds are handled by the Rails backend. How do we get them into the existing system?

**Comment by lennerd** [comment]
Related to #54

**Comment by 1000miles** [comment]
@lennerd 

Can you please check this file, if you already have updated the fixtures with the new node_types?
https://github.com/sozialhelden/wheelmap/blob/enhancement/new-node-types/spec/fixtures/node_types.yml

**Comment by lennerd** [comment]
That was the problem. Thank you! 🙈 

@1000miles suggested that it would be better to split this PR into smaller ones to be able to revert the database easier if something went wrong. I'll go for that. I will leave this PR open to save the important bits for the new PRs. cc @holgerd 

We also will need to wait until https://github.com/sozialhelden/wheelmap-privateissues/issues/3 is fixed.

**Pull request closed without merging**
