### PR TITLE
Add new node types to shopping category.

### PR DESCRIPTION
**Pull request by lennerd**

### CODE REVIEW

**Comment by 1000miles** [comment]
@lennerd can you please check this failure?

**Comment by lennerd** [comment]
I have absolutly no clue, why this tests are failing. Looks like the database is not working somehow. @schultyy @Hoverbear Do you have any ideas what the error messages are trying to tell us?

**Comment by lennerd** [comment]
Found the error. Fix is on the way.

**Comment by Hoverbear** [comment]
Ah the good old typo error. :)

**Comment by lennerd** [comment]
I rebased this PR to `enhancement/new-node-type-misc`.

**So, #379 needs to be merged first.**

**Comment by lennerd** [comment]
Seed and translation files are fixed and PR is again rebased on `enhancement/new-node-type-misc`.

**Comment by 1000miles** [comment]
So far it looks good. Please go ahead and merge, @lennerd. Thank you.

**Pull request merged**
