### PR TITLE
Upgrade accessibility.cloud widget to v3.2.1

### PR DESCRIPTION
**Pull request by opyh**
This is supposed to enable us to show Jaccede data on Wheelmap.

New features:
- Supports many more data attributes and renders them nicely for Jaccede.
- Better accessible for screen readers
- You can now navigate the entries using the keyboard (for example with arrow keys)
- Overall look’n’feel is a bit better, added icons and tooltips

Fixed:
- Items are only expandable when there is actual extra information additionally to wheelchair accessibility

New tech:
- Rewrote the whole thing based on React.js, which should simplify changing the widget in the future (and integrating it in the new frontend)
- Transifex translations can have variables now
- Removed jQuery dependency
- Added FlowType for type safety, this should avoid several classes of bugs

kapture 2017-05-01 at 20 15 42

Test here: http://192.168.33.10:3000/nodes/3438037622

This just shows AXSMaps results currently. I will switch on Jaccede results on the backend as soon as the changes are integrated.

### CODE REVIEW

**Comment by Hoverbear** [comment]
@opyh Sorry I didn't review this yet!

**Comment by Hoverbear** [comment]
screen shot 2017-05-12 at 10 39 13

Looks like there is a bug with the links produced?

Also, can you confirm that the items should not be expanding for Vozejkmap?

**Comment by emig** [comment]
@Hoverbear on the description of the PR (new features) this apply only to Jaccede

**Comment by emig** [comment]
@opyh can you bring up http://192.168.33.10:3000/nodes/3438037622 again? Can't easily find nodes with Jaccede data on our local running instace

**Comment by Hoverbear** [comment]
@emig 

> I will switch on Jaccede results on the backend as soon as the changes are integrated.

**Comment by emig** [comment]
ah, yep...

**Comment by opyh** [comment]
Thanks for the review!

I removed the address parts from the Vozejkmap PoI titles so they make more sense as links, and removed the duplicates. It's correct that the items are not expandable: Only items that contain additional information beyond basic wheelchair accessibility are expandable. Before you could expand items just to see the same information as above again, which didn't make much sense :) All of this is done on the backend, so it shouldn't block you.

But: From what I remember, the category names were translated when I tested the PR, in your screenshot I see an untranslated 'accomodation'. Will double-check that the widget actually requests the information in the given locale, and get back to you as soon as I know.

**Comment by opyh** [comment]
@emig http://192.168.33.10:3000/nodes/597928345 should give you some visible results. The accessibility details are not implemented in a Jaccede-specific way, so if they work on other sources, they work with Jaccede as well.

**Comment by opyh** [comment]
Another thing about Vozejkmap: Just saw that their API only delivers a link to the venue's own web page, not to Vozejkmap itself. We can differentiate between the two URLs in the data format, but the AC widget does not take the difference into account yet – will add this as a feature to the next version.

**Comment by emig** [comment]
LGTM after the fixes requested by @Hoverbear

**Comment by opyh** [comment]
- Fixed links that were missing `https://` prefix
- Double-checked locale – the widget requests locale correctly, nothing to change there (there's a bug in the backend when requesting locales with country code, as soon as the backend supports this, the widget will show correct categories. will fix this now, no merge blocker IMO)

**Comment by opyh** [comment]
The category translations are fixed now, too. Have a good weekend everyone ✨

**Comment by opyh** [comment]
@Hoverbear @emig Hopefully good to merge now? :)

**Comment by Hoverbear** [comment]
@opyh That problem is resolved. However now when I go to node 429739180 with Wheelmap sources excluded I get this:

screen shot 2017-05-18 at 10 22 21

I do not believe `object` is intended?

**Comment by opyh** [comment]
@Hoverbear Hmm, is there a misunderstanding, do you mean 'included'? I don't have 429739180 on my local DB, but on my machine, I see 'excludeSourceIds=LiBTS67TjmBcXdEmX' in the request and don't get any results on 1346939681, which is in the same street and expected behavior. Wheelmap is intentionally excluded in the widget. If you think we might misunderstand each other, you can also hit me up on Slack so we can sort this out :)

**Comment by opyh** [comment]
About 'object': We have a lot of old PoIs in our Wheelmap import that are just named 'object'. This is a known issue, but not 100% important right now – we can sort this out later.

**Comment by Hoverbear** [comment]
Sorry, my bad. With Wheelmap **included** in results.

**Comment by Hoverbear** [comment]
Ah okay, the note about nodes being `object` is fair. Is there any way we can confirm that this is the issue and not something else?

**Comment by opyh** [comment]
Here:

```bash
[hypo2:~/Desktop]$ curl 'https://www.accessibility.cloud/place-infos?includeRelated=source&locale=de&latitude=52.5074247&longitude=13.4221092&accuracy=1000&limit=10' -H 'x-token: 27be4b5216aced82122d7cf8f69e4a07' -H 'accept: application/json' | jq .features[].properties.name
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8225    0  8225    0     0  14290      0 --:--:-- --:--:-- --:--:-- 14304
"Tennisclub Berlin Mitte"
"object"
"object"
"object"
"object"
"object"
"object"
"Schiefe Locken"
"object"
"Schiefe Locken"
```

(btw, [`jq`](https://stedolan.github.io/jq/) is a wonderful debugging tool!)

**Comment by Hoverbear** [comment]
Yes `jq` is awesome. :)

**Pull request merged**
