### PR TITLE
Change community_center to community_centre

### PR DESCRIPTION
**Pull request by 1000miles**
PR for #87 

@lennerd Can you pls take a look here, if we are on the right path? Anything else we need to definitely consider for our further research & work? Thank you.

cc @schultyy

### CODE REVIEW

**Comment by lennerd** [comment]
Looks good to me. :+1:

**Comment by lennerd** [comment]
Can you deploy to staging?

**Comment by 1000miles** [comment]
@lennerd thank you.

regarding your deployment question: not yet. can you pls give @schultyy and me access?

**Comment by lennerd** [comment]
Please ask @Xylakant or @thermann78 for an access.

**Comment by polarbearing** [comment]
Thanks a lot. Please let me know here once it is deployed, so we can start reviewing the current tags in OSM. 

One question: the commit adds this class:
```class ChangeCommunityCenterToCommunityCentre < ActiveRecord::Migration```

Does this change the spelling in the database once a user reviews the facility, or does it run automatically through the data? The latter would be a mechanical edit that is discouraged.

**Comment by schultyy** [comment]
@polarbearing This change affects only newly created places with the node type community centre. We do not change already present data in OSM. For the places tagged with the old spelling we need to discuss how to proceed with those.

**Comment by polarbearing** [comment]
My plan was to write a mail to talk-de once the bug is fixed in wheelmap, to ask local mappers for verification and manual migration. There are also new tags that can be considered manually for detailed description such as the type community_centre=* and for whom community_centre:for=* 

So, what does this migration class do, just for understanding?
```db/migrate/20160112153334_change_community_center_to_community_centre.rb```

**Comment by schultyy** [comment]
This migration changes the spelling of community_center to community_centre in the wheelmap database. That value is then used when a user creates a new place via the wheelmap interface.

**Pull request merged**
