### PR TITLE
Migrate to mailgun

### PR DESCRIPTION
**Pull request by Hoverbear**
Migrates the application to use mailgun for mailing.

Addresses https://github.com/sozialhelden/wheelmap/issues/436 temporarily

### CODE REVIEW

**Comment by Xylakant** [comment]
well, I'd actually migrate in the direction of using the actual mailgun API over the smtp interface, but this should do to get it working on the new staging.

**Comment by Hoverbear** [comment]
That'd require moving away from ActionMailer to https://github.com/mailgun/mailgun-ruby.

**Comment by Hoverbear** [comment]
Verified this works on the new infra staging.

**Comment by Xylakant** [comment]
> That'd require moving away from ActionMailer to https://github.com/mailgun/mailgun-ruby.

Yes, we're aware. I'd keep the actual issue open and treat this as an intermediary step. The API is significantly superior when it comes to sending templated and bulk email

**Comment by Hoverbear** [comment]
Okay, sounds good.

**Comment by schultyy** [comment]
Related to #349

**Pull request merged**
